### ISSUE TITLE
zero copy support:master

### ISSUE THREAD

**Issue by ambitslix** [google/libnop#6]
Hello,

I've looked through the docs and examples and this library fits very well with my needs but I'm not finding an important feature which is to be able to do zero copy serialization of external data. An example of this is when you have image data that needs to be read as a binary blob as part of a structure. Like so:

struct Sprite{
 ...other members
 ...
 std::vector<uint8_t> img;
}

When writing such a struct I'd like to be able to directly read the image data into the serialization buffer. So it would be a API like so:
```
std::vector<uint8_t> buf(1024*1024);
nop::Serializer<nop::BufferWriter> encoder(buf.data(), buf.size());
int maxlen;
uint8_t* ptr = encoder.GetPtr(cost T& value, &maxlen); //Gets a pointer and maxlen only to the structure but doesn't copy anything

//...Here we can read image data directly into buf via read at ptr up to maxlen
...
int len = read(fd, ptr,maxlen);
...

encoder.Finish(len); //Finishes encoding the length 

```
This avoids expensive memcpy for large binary chunks. Should be restricted to last member, and vector types in order to avoid holes.

Is there a way to do this or something to add to the library? Seems pretty straightforward. It can be done with: [0xBC 0x82 LENGTH(uint32_t) ...data follows...] just to keep it simple always use 32 bit unsigned for length?

Thanks, Best
Mark

**Comment by eieio** [comment]
Hi Mark,

Thanks for your patience getting back to you.

Unfortunately, the serializer isn't designed to handle encoding from sources other than memory. It would be very easy to break the protocol otherwise, since the serializer wouldn't be sure about what happened between calls.

Are you on a platform that supports mmap? If that's the case, then there might be something we can add to support your use case.

The library supports a concept called [fungibility](https://github.com/google/libnop/blob/master/docs/getting-started.md#protocols-validation-and-fungibility), which means you can define several versions of a data type and the library can use any of them interchangeably, as long as they would produce the same format data. We can use this mechanism to write an alternate Sprite that can point to an mmap'ed file.

To expand on your example, it might look something like this:

```C++
// Define the primary protocol for a Sprite.
struct Sprite {
  // Other fields ...
  std::vector<uint8_t> img;

  NOP_STRUCTURE(Sprite, /* other fields */, img);
};

// Define an alternate data type that conforms to the Sprite protocol and can be used
// with mmap.
struct SpriteMmap {
  // Other fields ...
  size_t img_size;
  uint8_t* img_data;

  NOP_STRUCTURE(SpriteMmap, /* other fields */, (img_size, img_data));
};

// Make sure SpriteMmap is fungible with Sprite.
static_assert(nop::IsFungible<Sprite, SpriteMmap>

int fd = // Open file for reading.
const size_t file_size = // Size of image file in bytes.
uint8_t* img_data = mmap(nullptr, file_size, PROT_READ, MAP_SHARED, fd, /*offset*/ 0);

SpriteMmap sprite_file{/*other fields*/, file_size, img_data};

std::vector<uint8_t> buffer(nop::Encoding<SpriteMap>::Size(sprite_file));
nop::Serializer<nop::BufferEncoder> serializer{buffer.data(), buffer.size()};

serializer.Write(sprite_file);
```

Right now [logical buffers](https://github.com/google/libnop/blob/master/docs/getting-started.md#logical-buffers) only support grouping a size member with an array member, but we could add support for grouping a size member with a pointer member.

Does this sound like it would solve your problem?

**Comment by ambitslix** [comment]
Thanks, it would not work, but supporting zero copy is quite fundamental in my use case and I'm surprised that libraries don't support it. I'm using yas now where it is possible do to.
